### ISSUE TITLE
ROC API stopped working after node restart

### ISSUE THREAD

**Issue by pushpraj527** [onosproject/onos-config#1601]
We have deployed Aether on the GKE cluster. We have also enabled the persistence volume for onos-consensus-store
We observed that after the GKE Cluster restart (after the updates).

ROC API Seems not able to add/update the resources.
E.g. Add/Delete subscriber API returns success but, it is not doing what it is supposed to do.
It looks like an onos/atomix store issue.

We are using the following versions for the components:
Atomix-Controller:
    ChartVersion: 0.6.9
    AppVersion: v0.6.2
Atomix-Raft-Storage:
    ChartVersion: 0.1.25
    AppVersion: v0.9.19
ONOS-Operator:
    ChartVersion: 0.5.1
    AppVersion: v0.5.0
ONOS-Config:
    ChartVersion: 1.6.11
    AppVersion: v0.10.27
ONOS-topo:
    ChartVersion: 1.2.2
    AppVersion: v0.9.3
ONOS-Cli:
    ChartVersion: 1.2.7
    AppVersion: v0.9.10

Logs:
      -> One transaction is stuck reporting the following error:
``` 
        2022-11-09T12:27:52.616Z    ERROR    controller/configuration    configuration/controller.go:219    Failed sending SetRequest prefix:{target:"connectivity-service-v2"...
(EXTRA *errors.TypedError=error in creating config struct from IETF JSON data: field name SimCard value sim-312440000001123 
(string ptr) schema path /device/enterprises/enterprise/site/device/sim-card has leafref path ../../sim-card/sim-id not equal to any target nodes)
[github.com/onosproject/onos-config/pkg/controller/configuration.(*Reconciler).reconcileConfiguration](http://github.com/onosproject/onos-config/pkg/controller/configuration.%28*Reconciler%29.reconcileConfiguration)
    /build/pkg/controller/configuration/controller.go:219
[github.com/onosproject/onos-config/pkg/controller/configuration.(*Reconciler).Reconcile](http://github.com/onosproject/onos-config/pkg/controller/configuration.%28*Reconciler%29.Reconcile)
    /build/pkg/controller/configuration/controller.go:76
[github.com/onosproject/onos-lib-go/pkg/controller.(*Controller).reconcileRequest](http://github.com/onosproject/onos-lib-go/pkg/controller.%28*Controller%29.reconcileRequest)
    /build/vendor/[github.com/onosproject/onos-lib-go/pkg/controller/controller.go:282](http://github.com/onosproject/onos-lib-go/pkg/controller/controller.go:282)
[github.com/onosproject/onos-lib-go/pkg/controller.(*Controller).reconcileRequests](http://github.com/onosproject/onos-lib-go/pkg/controller.%28*Controller%29.reconcileRequests)
    /build/vendor/[github.com/onosproject/onos-lib-go/pkg/controller/controller.go:275](http://github.com/onosproject/onos-lib-go/pkg/controller/controller.go:275)
```     
It’s still reattempting it. We tried to get the particular SIM Object for the specified id but, it’s structure seems fine. not sure if it Persistent volume corruption issue. But, it has to stop somewhere. it still continuously reattempts the same operation. 
This is preventing further new transactions.

onos-consensus-store config override:
```
global:
  storage:
    controller: "atomix-controller.kube-system:5679"
  store:
    consensus:
      enabled: true
      clusters: 1
      replicas: 1
      partitions: 1
      persistence:
        storageClass: "silver"
        storageSize: 5Gi

``` 

onos-config override:
```
onos-config:
  logging:
    loggers:
      root:
        level: debug
  store:
    consensus:
      enabled: false
```
